spring:
  application:
    name: ms-main
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  datasource:
    url: ${DBCP_MSDB_URL}
    username: ${DBCP_MSDB_USER}
    password: ${DBCP_MSDB_PASS}
    driver-class-name: ${DBCP_MSDB_DRIVER}
    hikari:
      maximum-pool-size: ${DBCP_GENERIC_MAX_POOL_SIZE}
      auto-commit: ${DBCP_GENERIC_AUTO_COMMIT}
      connection-timeout: ${DBCP_GENERIC_CONNECTION_TIMEOUT}
      max-lifetime: ${DBCP_GENERIC_MAX_LIFE_TIME}
      minimum-idle: ${DBCP_GENERIC_MIN_IDLE}

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

application:
  security:
    jwt:
      secret-key: j8dSIsqUb5oti6csIEOs0zTvTLbuMv9J7C8yCqjZ8iYelIhLWlNsccsrbeAYT/h144RPPE7h94xtdRsp8yOFNA==
      expiration: 86400000
